name: Docker Image CI

on:
  push:
    branches: [ "belce" ]
  pull_request:
    branches: [ "belce" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Log in to the Container registry
    - name: Log in to the Container registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # Set up variables
    - name: Set up variables
      run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

    # Build the Docker image
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag aichan-belce:${{ env.BRANCH_NAME }} --tag ghcr.io/aitorastorga/aichan-belce:${{ env.BRANCH_NAME }}
        # If the branch is main, also tag as latest
        if [ "${{ env.BRANCH_NAME }}" == "main" ]; then
          docker tag aichan-belce:main ghcr.io/aitorastorga/aichan-belce:latest
        fi

    # Push the Docker images to GHCR
    - name: Push Docker images to GHCR
      run: |
        docker push ghcr.io/aitorastorga/aichan-belce:${{ env.BRANCH_NAME }}
        # If the branch is main, also push the latest tag
        if [ "${{ env.BRANCH_NAME }}" == "main" ]; then
          docker push ghcr.io/aitorastorga/aichan-belce:latest
        fi
